const char exfile[] =
"# ------------------------------------------------------------ \n"
"# Example file, ex/1tasks.ts\n"
"# ------------------------------------------------------------ \n"
"#\n"
"# tasks -- top level container for all tasks\n"
"#\n"
"tasks = (\n"
"    {\n"
"        name = \"t.1\";\n"
"	period = 8;\n"
"	deadline = 8;\n"
"	threads = 1;\n"
"	wcet = (2);  # WCET of 1 thread\n"
"    },\n"
"    {\n"
"        name = \"t.2\";\n"
"	period = 8;\n"
"	deadline = 8;\n"
"	threads = 3;\n"
"	wcet = (6, 2, 2); #WCET of 1, 2, or 3 threeds\n"
"    }\n"
");\n";
