const char exfile[] =
"\n"
"# ------------------------------------------------------------ \n"
"# Example file, ex/uunifast.ts \n"
"# ------------------------------------------------------------ \n"
"#\n"
"# tasks -- top level container for all tasks\n"
"#\n"
"tasks = (\n"
"    {\n"
"	name = \"t.1\";\n"
"	period = 8;\n"
"	deadline = 8;\t# ignored, not modified\n"
"	threads = 0;\t# indicates that the WCET will be changed\n"
"	wcet = ();\t# <-- Will be modified\n" 
"    },\n"
"    {\n"
"	name = \"t.2\";\n"
"	period = 0;		# indicates that the period will be changed\n"
"	deadline = 8;\n"
"	threads = 3;\n"
"	wcet = (6, 8, 10);	# WCET of 10 will be used\n"
"    }\n"
");\n";
